name: hello world 

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
      
  workflow_dispatch:

jobs:
 hello_world:
   runs-on: ubuntu-latest
   steps:
     - uses:  actions/checkout@v2
     - name:  hello world
       run: echo "hello world from work flow"
       shell: bash
